# Generated by Django 5.2.7 on 2025-10-30 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSystemMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_user_id', models.CharField(max_length=50, unique=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_mappings', to='rooms.system')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_mappings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'system')},
            },
        ),
    ]
